### ISSUE TITLE
Docs don't reflect renamed actions

### ISSUE THREAD

**Issue by javalasers** [isaacwisdom/RemarkableLamyEraser#60]
https://github.com/isaacwisdom/RemarkableLamyEraser/blob/8b8f163fd09586e789cdf72c161d2144247ebfa5/config/LamyEraser.conf#L21

On this line, should be eraser-selection (not erase-selection). And a few lines down in the example, should be eraser-erase (not just "erase")...

**Comment by javalasers** [comment]
[This was in the v2-3.0.0-fix branch]

**Comment by isaacwisdom** [comment]
Fixed with 00f1d76

**Comment by javalasers** [comment]
You missed lines 21 (should be eraser-selection) and 25 (eraser-erase), I
think...

**Comment by isaacwisdom** [comment]
Fixed with 4d3c83f
